# Site settings
title: HS explorer
email: youremailaddress@gmail.com
description: "Empowering Your Trade: Simplifying HS Classification for Seamless Business"
# description: We provide the most powerful HS classification services to simplify your trade procedure.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url:
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown
